spring.application.name=${APP_NAME}
spring.config.import=optional:file:.env[.properties]
#Conexion a la base de datos
spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Se crea las tablas de la  base de datos de foram automatica si no existe
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Hibernate 7 ya detecta automaticamente la versiond emysql

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#foramto sql legible y ordenado
spring.jpa.properties.hibernate.format_sql=true


#Pool de conexiones
#Espera 30 segundos por una conexion
spring.datasource.hikari.connection-timeout=${CONNECTION_TIMEOUT}
#Numero maximo de conexiones simultaneas
spring.datasource.hikari.maximum-pool-size=${MAXIMUM_POOL_SIZE}

#Cambiar el contextpath para la app
server.servlet.context-path=${SERVER_PATH}

#Configurar Patron del log (en vez de logbackspring.xml)
logging.pattern.console=[%tread] %-5level: %logger -$msg%n
#Configurar el nivel de log
logging.level.root=INFO

#MOstrar abnner sping boot al ejecutar
spring.main.banner-mode=off

#Cmaiar el puerto
server.port=${PORT:8080}

# CORS y URL
# CORS
app.cors.allowed-origins=${APP_CORS_ORIGINS}
app.base-url=${APP_BASE_URL}

